main: me.CarsCupcake.SkyblockRemake.Main
name: SkyblockRemake
version: 0.2.6
author: CarsCupcake
api-version: 1.17
depend:  [FastAsyncWorldEdit]

commands:
  gm:
    describtion: "Quick Gamemode Toggle"
  item:
    describtion: "Get Custom items"
  npc:
  terminal:
  lavabounce:
  statsystem:
  healthitems:
  stats:
    usage: /stats <stat> <amount>
  e:
  testobject:
  spawns:
  part:
  slayer:
  beacon:
  laser:
  ench:
    describtion: Custom enchants
  av:
    describtion: Opens an anvil
  reforge:
  coins:
  canon:
  kuudra:
  generate:
  accessoryslots:
  unlockpowers:
  event:
  addpetxp:
  addskillxp:
  dungeon:
  giveeditionitem:
  startboss:
  craft:
  selectmob:
  entitynpc:
  deliver:
  mob:
  setting:
  dummy:
  star:
  potion:
  ah:
  bz:
  fixenchants:
  undozap:
  setcounter:
  max:
  loadschematic:
  room:
  quest:
  rifttime:
  wd:
    aliases:
      - wardrobe
  wardrobe:
    aliases:
      - wd
  drhelp:
    description: command for a staff
  compile:
    description: command for a staff
  gemstonegrinder:
    description: opens the Gemstone Grinder
    aliases: gsg
  gsg:
    description: opens the Gemstone Grinder
    aliases: gemstonegrinder
